name: Publish package to GitHub Packages
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Set version to SNAPSHOT
        run: echo "version=$(./gradlew properties -q | grep "version:" | awk '{print $2}')-SNAPSHOT" >> $GITHUB_ENV
      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish -Pversion=$version
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          version: ${{ env.version }}